# _config.yml
title: Bread and Letters Blog
email: academy@breadandletters.com
description: >-
  Insights, tips and stories for ambitious young professionals in South East Asia.
  Articles on Excel, Power BI, workplace skills, fiction, history and culture.
baseurl: ""
url: "https://blog.breadandletters.com"

# Social media
twitter_username: breadandletters
github_username: breadandletters

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

# Custom variables
academy_url: "https://academy.breadandletters.com"
blog_url: "https://blog.breadandletters.com"

# Disqus Comments
disqus:
  shortname: "b-l" # Replace this with your actual shortname


# Social media links
social:
  linkedin: "https://linkedin.com/company/breadandletters"
  instagram: "https://instagram.com/breadandletters"
  twitter: "https://twitter.com/breadandletters"